### ISSUE TITLE
Not an issue: Can you give a howto on the bluetooth?

### ISSUE THREAD

**Issue by dreuf83** [dreadnought/python-daly-bms#12]
How do I connect this software to bluetooth?

**Comment by dreadnought** [comment]
The CLI tool doesn't have the functionality to connect via Bluetooth implemented yet, only the Python module does.

If you are interested in integrating it in your own application, have a look here:
https://github.com/dreadnought/energy-storage-controller/blob/master/smart_bms.py

This service uses the `DalyBMSBluetooth` class to connect via Bluetooth and push the data to an InfluxDB.
