### ISSUE TITLE
Not an issue - how to use bluetooth script

### ISSUE THREAD

**Issue by icenov** [dreadnought/python-daly-bms#19]
I can see that the cli code calls in the python modules, but how can I use the python bluetooth module on its own? When I run the code it runs without error, but that is expected as it is creating the Class etc. How do I actually connect with BT and call the functions?

**Comment by dreadnought** [comment]
Here you can see an example of a daemon that uses the Bluetooth module and sends the data to InfluxDB: https://github.com/dreadnought/energy-storage-controller/blob/master/smart_bms.py

The Bluetooth library uses asyncio, so the code using it has to be aware of that and wait for the results results.
