### ISSUE TITLE
Voltage of single cell jumps alot

### ISSUE THREAD

**Issue by BjoernRave** [dreadnought/python-daly-bms#27]
The voltage of my 1. cell is different with every request. These requests were made directly after each other:
```
{
  "1": 4.258,
  "2": 3.367,
  "3": 3.369,
  "4": 3.366
}
pi@raspberrypi-main:~ $ daly-bms-cli -d /dev/ttyUSB0 --cell-voltage
{
  "1": 3.868,
  "2": 3.367,
  "3": 3.368,
  "4": 3.366
}
pi@raspberrypi-main:~ $ daly-bms-cli -d /dev/ttyUSB0 --cell-voltage
{
  "1": 4.444,
  "2": 3.367,
  "3": 3.369,
  "4": 3.37
}
pi@raspberrypi-main:~ $ daly-bms-cli -d /dev/ttyUSB0 --cell-voltage
{
  "1": 4.307,
  "2": 3.366,
  "3": 3.368,
  "4": 3.363
}
pi@raspberrypi-main:~ $ daly-bms-cli -d /dev/ttyUSB0 --cell-voltage
{
  "1": 4.383,
  "2": 3.366,
  "3": 3.369,
  "4": 3.365
}
pi@raspberrypi-main:~ $ daly-bms-cli -d /dev/ttyUSB0 --cell-voltage
{
  "1": 4.463,
  "2": 3.366,
  "3": 3.369,
  "4": 3.365
}
```
The iOS app `SmartBMS` is telling me that the 1. cell is at around 3.6v.

**Comment by dreadnought** [comment]
Hi,
I see this behavior when the battery gets discharged, not while being idle or charging. The same happens to the `current` in `--soc`, while the `total_voltage` is stable.

![screenshot-bms](https://user-images.githubusercontent.com/13079298/162399900-b572b6f7-8f61-40d6-97ab-bb198ceae4bd.png)

I don't know why it happens or what the mobile app does different. As far as I can see there is nothing wrong in the communication, the BMS sends the values like we see them. If you want it to look better in the visualization, you can calculate the moving average to make the chart look smoother.

![screenshot-bms-moving-average](https://user-images.githubusercontent.com/13079298/162402331-dd660661-30ba-482a-924a-e3bbdf985613.png)
