### ISSUE TITLE
multiple boards

### ISSUE THREAD

**Issue by melaz** [dreadnought/python-daly-bms#32]
Hi, is there a way to monitor 2+ boards via RS485 with one adapter and this software?

**Comment by dreadnought** [comment]
Hi,
I think the BMS itself doesn't support that. You can't set different addresses for each BMS, like you would do it for other RS485 devices. And without that you can't send a command to a specific BMS and don't know who's answer you're receiving. 

The options that I see are either multiple USB adapters or using a Bluetooth adapter that connects to one MAC address after the other.

**Comment by PRIMETSS** [comment]
Shame they didn't support STD Modbus Protocol and wrote their own
