### ISSUE TITLE
--sinowealth —all

### ISSUE THREAD

**Issue by Achilles160716** [dreadnought/python-daly-bms#7]
this brings an error that getall is not implemented…. i would like to integrate it in my system and send every minute this request. 

daly-bms-cli: error: unrecognized arguments: --getall

the rest is working! great job

**Comment by dreadnought** [comment]
Hi,
I've implemented it for the Sinowealth BMS now. Have in mind that it's `--all` not getall when you're testing it.

**Comment by Achilles160716** [comment]
hi

good evening. i will test it tomorrow morning. getting late here. 

thank you 


Achilles
